# Generated by Django 3.1.1 on 2020-10-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.FloatField(default=12, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='lon',
            field=models.FloatField(default=1, verbose_name='Долгота'),
            preserve_default=False,
        ),
    ]
