# Generated by Django 3.1.1 on 2021-01-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20210110_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default=' ', upload_to='', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
