# Generated by Django 3.1.1 on 2021-01-20 06:28

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_auto_20210118_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='long_description',
            field=tinymce.models.HTMLField(default='', verbose_name='Подробное описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='short_description',
            field=models.TextField(default='', verbose_name='Короткое описание'),
            preserve_default=False,
        ),
    ]
